### ISSUE TITLE
Change ph5tomsAPI to not access (open) a PH5 file for every request

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#3]
Our method for adding support for HTTP POST request to the web service has consequently caused the program to produce a list of requests, where each request in the list contains only one (SNCL) Network, Station, Location, Channel, Starttime (ST), and Endtime (ET). The program then calls the ph5tomsAPI for each request in the list, causing the program open the PH5 experiment many times.

We propose a solution where the ph5tomsAPI.PH5toMSeed class constructor can accept an optional PH5API object. This would allow the program to read the PH5 experiment once per network (experiment), and reuse the same PH5API object for each subsequent SNCL<ST><ET> request for that network.

I'm not sure of all the details that would be involved in this implementation, but this is the basic concept. A similar implementation will also be needed in the ph5tostationxml.py program, and the [ph5tosegyAPI](https://github.com/PIC-IRIS/PH5/issues/2) once it is completed. Thoughts?

**Comment by derick-hess** [comment]
This is doable and really it makes sense in the long run to just pass a ph5API object anyway since ph5tomsAPI is a module. It not only addresses this issue but makes sense if someone were to want to use ph5tomsAPI as a module in some future software they are making that may use ph5API objects in multiple ways.
