### ISSUE TITLE
PH5toStationXML Response Management

### ISSUE THREAD

**Issue by derick-hess** [PIC-IRIS/PH5#81]
We need to add a key for sample rate. Since there are different responses based on sample rate that can have the same sensor_key and data_logger key, another ket based on sample_rate needs to be added.

I found this when the VM stations were added. There is now response for VM currently in the PH5, but I noticed since they are still cmg-3t/rt130 instruments, it's using the last loaded response and loading that into the inventory object as the response for the VM channels.

I think this error would only ever come up if there is no response for a channel and it matched keys from a previous channel.

**Comment by nick-iris** [comment]
This shouldn't be a problem to add. You can just add them to the sensor_keys. The ResponseManager just checks if a response was already read, so that the program isn't reading the RESP file for every channel.

I think something like this on ph5tostationxml.py lines 364-366 would be all that is needed:
```
        sensor_keys = [obs_channel.sensor.manufacturer,
                       obs_channel.sensor.model,
                       obs_channel.sample_rate]
```

Note the addition of the sample rate the sensor_keys list.

**Comment by derick-hess** [comment]
Thanks. I'll fix it and run some tests today.
